const GET_RACES = 'GET_RACES';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const FILTER_OF_TEMPERAMENTS = 'FILTER_OF_TEMPERAMENTS';
const FILTERED_RACES_CREATED = 'FILTERED_RACES_CREATED';
const ORDER_BY_NAME = 'ORDER_BY_NAME'



module.exports = {
    GET_RACES,
    FILTER_OF_TEMPERAMENTS,
    GET_TEMPERAMENTS,
    FILTERED_RACES_CREATED,
    ORDER_BY_NAME
}