const GET_RACES = 'GET_RACES';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const FILTER_OF_TEMPERAMENTS = 'FILTER_OF_TEMPERAMENTS';



module.exports = {
    GET_RACES,
    FILTER_OF_TEMPERAMENTS,
    GET_TEMPERAMENTS
}